data:
  train_validation_set_directory: "../MNIST/train"
  test_set_directory: "../MNIST/test"
  train_set_length: 0.9
  validation_set_length: 0.1

train:
  device: "cuda"
  noise_dimension: 64
  learning_rate: 0.00001
  epochs: 200
  batch_size: 128
  # TODO: bug for not considering all batches, calculated only within current batch, value>step_size won't work, fix
  show_and_save_by: 420 

logging:
    directory: "experiments"
    sub_directory: "Experiment 1"
    model_name: "GAN"
  
model:
  results: "results"
  save_directory: "models"
  name: "GAN_1"


